### ISSUE TITLE
Depedency versions

### ISSUE THREAD

**Issue by ghost** [isomorphic-typescript/ts-monorepo#4]
I'm trying to add a Vue v3 project. However when using this amazing tool, it seems to use the latest stable build of each package. So in my case the latest stable build for Vue is v2 so that is used instead of v3. Is it currently possible to specify a version of a package to use?

I rely on 2 local packages so I need to go through lerna/ts-monorepo, but it is currently a blocker because I can't use a specific version for a package.

**Comment by ozyman42** [comment]
I ran into this as well which is addressed in the latest version of ts-monorepo which I haven't published yet. It does change around how some things work though. You use Yarn workspaces instead of lerna for example, and the structure of the `ts-monorepo.json` changed a bit too.

If you're interested then you can use the `next` version of `ts-monorepo` to try it out. Then when specifying dependencies, you can supply a plain array to use latest stable version or a tuple for a specific version. So for example in one of my projects https://github.com/skoville/webpack-hot-module-replacement/blob/master/ts-monorepo.json#L70-L73

```
"devDependencies": [
  "ts-nameof",
  ["typescript", "3.9.5"]
]
```

this means use latest stable `ts-nameof` but specific version of `typescript`

**Comment by ozyman42** [comment]
With the latest release it now works in the way as described above (you can specify a specific version using a tuple or use a plain string for the latest stable release). Closing this one.
